const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function boot(prefs=null,features=["bg","point","road","building"]){const messages=[],events={},container={id:'amap-global-container',isConnected:true,getBoundingClientRect:()=>({left:10,top:20,right:810,bottom:620,x:10,y:20,width:800,height:600})};const window={addEventListener:(n,f)=>(events[n]??=[]).push(f),postMessage:q=>messages.push(q)};let reloaded=false;const saved={value:prefs?JSON.stringify(prefs):null};const ctx=vm.createContext({window,sessionStorage:{getItem:()=>saved.value,setItem:(_k,v)=>saved.value=v},location:{origin:'https://www.amap.com',reload:()=>reloaded=true},setInterval:()=>0,clearInterval:()=>{},requestAnimationFrame:f=>f(),console});vm.runInContext(fs.readFileSync(require.resolve('../extension/bridge.js'),'utf8'),ctx);class Map{constructor(_id,opts){this.options=opts;this.features=features.slice();}getFeatures(){return this.features.slice();}setFeatures(v){this.features=v.slice();}getContainer(){return container;}on(){}off(){}setCenter(p){this.center=p;}lngLatToContainer(p){return new window.AMap.Pixel(p.lng*2,p.lat*3);}containerToLngLat(p){return new window.AMap.LngLat(p.x/2,p.y/3);}}window.AMap={};window.AMap.Pixel=class{constructor(x,y){this.x=x;this.y=y;}getX(){return this.x;}getY(){return this.y;}};window.AMap.LngLat=class{constructor(lng,lat){this.lng=lng;this.lat=lat;}getLng(){return this.lng;}getLat(){return this.lat;}};window.AMap.Map=Map;const map=new window.AMap.Map("amap-global-container",{zoom:13});function send(q,origin='https://www.amap.com'){for(const fn of events.message)fn({source:window,origin,data:{channel:'region-notes-map-v1',direction:'to-map',...q}});}return{messages,map,send,saved,reloaded:()=>reloaded};}
test('late AMap constructor capture adopts map without needing private app state',()=>{const b=boot();b.send({type:'status'});assert.ok(b.messages.some(m=>m.type==='status'&&m.ready));});
test('projection and picking include container offset and round-trip geographic coordinates',()=>{const b=boot();b.send({type:'project',requestId:1,items:[{id:'a',coordinates:[[120,30]]}]});const r=b.messages.find(m=>m.type==='projected');assert.equal(JSON.stringify(r.items[0].points),'[[250,110]]');b.send({type:'pick',requestId:2,x:250,y:110});assert.equal(JSON.stringify(b.messages.find(m=>m.type==='picked').coordinate),'[120,30]');});
test('bridge rejects other origins and malformed coordinates without executing arbitrary methods',()=>{const b=boot();const n=b.messages.length;b.send({type:'focus',coordinate:[120,30]},'https://example.com');assert.equal(b.messages.length,n);assert.equal(b.map.center,undefined);b.send({type:'project',items:[{id:'a',coordinates:[[999,30]]}]});assert.ok(b.messages.some(m=>m.type==='error'));});

test('POI toggle preserves roads and buildings and restores the original point visibility',()=>{const b=boot();b.send({type:'poi-labels',hidden:true});assert.deepEqual(b.map.features,['bg','road','building']);b.send({type:'poi-labels',hidden:true});b.send({type:'poi-labels',hidden:false});assert.ok(b.map.features.includes('point'));assert.ok(b.map.features.includes('road'));});
test('restoring POIs does not enable a point layer that was originally absent',()=>{const b=boot(null,['bg','road']);b.send({type:'poi-labels',hidden:true});b.send({type:'poi-labels',hidden:false});assert.deepEqual(b.map.features,['bg','road']);});
test('full labels are disabled at construction while original map options survive',()=>{const b=boot({full:true,poi:false});assert.equal(b.map.options.showLabel,false);assert.equal(b.map.options.zoom,13);});
test('full-label preference persists before refresh and disabling leaves SDK defaults untouched',()=>{const b=boot();b.send({type:'full-labels',hidden:true});assert.equal(JSON.parse(b.saved.value).full,true);assert.equal(b.reloaded(),true);const normal=boot({full:false,poi:false});assert.equal(normal.map.options.showLabel,undefined);});
test('saved POI preference applies again when the map is constructed',()=>{const b=boot({full:false,poi:true});assert.ok(!b.map.features.includes('point'));b.send({type:'label-status'});assert.equal(b.messages.at(-1).poiHidden,true);});
