globalThis.crypto=require('node:crypto').webcrypto;
const {test}=require('node:test');const assert=require('node:assert/strict');const C=require('../extension/core.js');
function seed(){const p=C.project('测试项目');const f=C.feature('point',[[120.15,30.25]],p.categories[0].id);f.name='湖畔酒店';p.features.push(f);return p;}
test('full backup restores stable feature IDs, fields, geometry and photo bytes into new project',()=>{const p=seed();p.features[0].photos.push({id:C.uid(),name:'门头.jpg',data:'data:image/jpeg;base64,YWJj'});p.features[0].fields={房间数:30,已核实:true};const q=C.restore(C.backup(p));assert.notEqual(p.id,q.id);assert.deepEqual(q.features,p.features);assert.deepEqual(q.categories,p.categories);});
test('CSV round trip handles commas, quotes, multiline and spreadsheet formula escaping',()=>{const p=seed(),f=p.features[0];f.name='=HYPERLINK("bad")';f.notes='含逗号,及"引号"\n第二行';f.tags=['湖畔','酒店'];f.fields={价格:'100,200'};const plan=C.planCSV(p,C.toCSV(p));assert.equal(plan.updated,1);assert.equal(plan.added,0);assert.deepEqual(plan.errors,[]);assert.deepEqual(plan.project.features[0].notes,f.notes);assert.equal(plan.project.features[0].name,f.name);assert.ok(C.toCSV(p).includes("'=HYPERLINK"));});
test('CSV preserves photos and optional blank values on update',()=>{const p=seed();p.features[0].notes='保留';p.features[0].photos=[{id:'p',name:'x',data:'data:image/png;base64,YQ=='}];const input=`id,name,longitude,latitude,crs,notes\n${p.features[0].id},新名称,121,31,GCJ-02,`;const result=C.planCSV(p,input);assert.deepEqual(result.errors,[]);assert.equal(result.project.features[0].notes,'保留');assert.deepEqual(result.project.features[0].photos,p.features[0].photos);assert.equal(p.features[0].name,'湖畔酒店');});
test('invalid coordinates, wrong CRS, duplicate IDs and malformed tags block entire import',()=>{const p=seed();for(const row of ['a,A,,30,GCJ-02','a,A,120,30,WGS84','a,A,120,90,GCJ-02','a,A,120,30,GCJ-02\na,B,121,31,GCJ-02']){const result=C.planCSV(p,'id,name,longitude,latitude,crs\n'+row);assert.ok(result.errors.length);assert.equal(p.features.length,1);}assert.throws(()=>C.parseCSV('a,b\n"unterminated,2'));});
test('CSV mapping supports custom Chinese headers and appends category',()=>{const p=seed();const r=C.planCSV(p,'名称,经度,纬度,坐标系,类型\n景点,120,30,GCJ-02,景点',{name:0,longitude:1,latitude:2,crs:3,category:4});assert.equal(r.added,1);assert.deepEqual(r.errors,[]);assert.ok(r.project.categories.some(c=>c.name==='景点'));});
test('schema rejects executable attachments, invalid shapes, prototype fields and duplicate category IDs',()=>{const p=seed();let q=C.clone(p);q.features[0].photos=[{id:'x',name:'x',data:'data:image/svg+xml;base64,YQ=='}];assert.throws(()=>C.validate(q));q=C.clone(p);q.features[0].type='polygon';assert.throws(()=>C.validate(q));q=C.clone(p);q.features[0].fields=JSON.parse('{"__proto__":"x"}');assert.throws(()=>C.validate(q));q=C.clone(p);q.categories.push(q.categories[0]);assert.throws(()=>C.validate(q));});
test('filtering respects category visibility and custom fields',()=>{const p=seed();p.features[0].fields={用途:'商业'};assert.equal(C.visible(p,'商业').length,1);p.categories[0].visible=false;assert.equal(C.visible(p,'商业').length,0);});
test('geographic circle is closed and about one kilometer north at first vertex',()=>{const ring=C.ring([120,30],1000);assert.equal(ring.length,65);assert.ok(Math.abs(ring[0][1]-30-1000/111195)<0.00001);assert.ok(Math.abs(ring[0][0]-ring[64][0])<1e-9);});
test('non-point features never silently enter CSV as points',()=>{const p=seed();p.features.push(C.feature('line',[[120,30],[121,31]],p.categories[0].id));assert.equal(C.parseCSV(C.toCSV(p)).length,2);});
