(async()=>{
  'use strict';
  const C=NoteCore,S=NoteStore,$=s=>document.querySelector(s);
  const manager=new URLSearchParams(location.search).has('manager'),bus=NoteSync;
  document.body.classList.add(manager?'manager':'map-panel');document.title=manager?'区位笔记 · 数据管理':'区位笔记';
  const suppliedOrigin=new URLSearchParams(location.search).get('parentOrigin');
  const parentOrigin=suppliedOrigin&&/^https:\/\/(www\.)?amap\.com$/.test(suppliedOrigin)?suppliedOrigin:(document.referrer?new URL(document.referrer).origin:location.origin);
  const send=(type,data={})=>!manager&&parent.postMessage({channel:'region-notes-panel',type,...data},parentOrigin);
  let p,projects=[],selected='',activeCategory='',query='',mode='select',draft=[],ready=false,undo=[],redo=[],saving=Promise.resolve(),saveError=null,toastTimer,photoBusy=false;
  const revisions=new Map();let categoryFilter='',kindFilter='',sortBy='updated',mapPeer=null,externalPending=false,refreshTask=Promise.resolve();
  const el=(tag,attrs={},txt)=>{const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='class')n.className=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2),v);else if(k==='value')n.value=v;else n.setAttribute(k,String(v));}if(txt!==undefined)n.textContent=txt;return n;};
  function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
  function on(selector,event,fn){$(selector).addEventListener(event,async e=>{try{await fn(e);}catch(err){toast(err.message);}});}
  function persist(){
    if(!p)return Promise.resolve();
    const snapshot=C.clone(p);$('#save-status').textContent='正在保存…';
    saving=saving.then(async()=>{
      if(saveError)throw saveError;
      const out=await S.save(snapshot,revisions.get(snapshot.id)||0);revisions.set(out.id,out.revision);
      if(p.id===out.id)p.revision=out.revision;
      $('#save-status').textContent='已保存在本机';$('#save-status').className='';
    }).catch(err=>{saveError=err;$('#save-status').textContent='保存失败 · 请备份';$('#save-status').className='error';toast(err.message);});
    return saving;
  }
  function commit(fn){
    if(!p)throw Error('请先新建或选择一个项目。');if(saveError||externalPending)throw Error('请先导出当前备份，再载入最新数据。');
    const prev=C.clone(p);try{fn();p=C.validate(p);}catch(err){p=prev;throw err;}
    undo.push(prev);if(undo.length>30)undo.shift();redo=[];persist();render();
  }
  function scene(){if(manager)return;if(!p){send('scene',{features:[],categories:[],name:'',selected:''});return;}const features=C.visible(p,query);send('scene',{features:features.map(({id,type,coordinates,name,categoryId,radius})=>({id,type,coordinates,name,categoryId,radius})),categories:p.categories,name:p.name,selected});}
  const hints={select:'选择工具，在地图上标注；拖动地图可浏览。',point:'点击地图放置点位。',line:'点击确定节点，虚线实时预览；双击或 Enter 完成。',polygon:'逐点圈定范围，点击起点闭合；双击或 Enter 完成。',circle:'先点击圆心，再移动鼠标并点击确定半径。',text:'点击放置文字。',edit:'在地图上编辑节点或整体移动，完成后保存。'};
  function setMode(v,move=false){
    const target=v==='edit'?p.features.find(f=>f.id===selected):null;if(v==='edit'&&!target)return;
    if(!p&&v!=='select')return;mode=v;draft=[];const cat=p?.categories.find(c=>c.id===(target?.categoryId||activeCategory));
    send('mode',{mode:v,target:target?{id:target.id,type:target.type,coordinates:target.coordinates,radius:target.radius}:null,color:cat?.color||'#147d6b',move,hint:hints[v]});renderTools();scene();
  }
  function renderTools(){for(const b of document.querySelectorAll('[data-mode]')){b.classList.toggle('active',b.dataset.mode===mode);b.disabled=(!ready||!p||manager)&&b.dataset.mode!=='select';}$('#draw-hint').textContent=ready?hints[mode]:'尚未连接地图。安装后刷新高德页面；若仍失败，请保留备份并反馈网页版本。';$('#draw-actions').hidden=true;$('#finish').disabled=draft.length<(mode==='line'?2:3);$('#back-vertex').disabled=!draft.length;$('#undo').disabled=!undo.length;$('#redo').disabled=!redo.length;}
  function renderProjects(){const sel=$('#projects');sel.replaceChildren(...projects.map(v=>el('option',{value:v.id},v.id===p?.id?p.name:v.name)));sel.value=p?.id||'';const rail=$('#project-rail');rail.replaceChildren();if(manager)for(const v of projects){const b=el('button',{class:'project-item'+(v.id===p?.id?' selected':''),'aria-label':`打开项目${v.name}`});b.append(el('strong',{},v.id===p?.id?p.name:v.name),el('small',{},`${(v.id===p?.id?p:v).features.length} 个标注`));b.onclick=()=>openProject(v.id).catch(e=>toast(e.message));rail.append(b);}$('#rename-project').disabled=$('#delete-project').disabled=!p;}

  function renderCategories(){const box=$('#categories');box.replaceChildren();for(const c of p.categories){
    const row=el('div',{class:'category'}),cb=el('input',{type:'checkbox','aria-label':`显示${c.name}`});cb.checked=c.visible;cb.onchange=()=>commit(()=>{c.visible=cb.checked;});
    const choose=el('button',{class:`choose ${c.id===activeCategory?'active':''}`,title:`使用${c.name}绘制`}),dot=el('span',{class:'dot'});dot.style.background=c.color;choose.append(dot);choose.onclick=()=>{activeCategory=c.id;renderCategories();};
    const edit=el('button',{class:'link',title:`管理分类${c.name}`,'aria-label':`管理分类${c.name}`},'⋯');edit.onclick=()=>categoryMenu(c);
    row.append(cb,choose,el('span',{class:'category-name'},c.name),el('span',{class:'category-count'},String(p.features.filter(f=>f.categoryId===c.id).length)),edit);box.append(row);
  }}
  function tableFeatures(){const searchable={...p,categories:p.categories.map(c=>({...c,visible:true}))};return C.visible(searchable,query).filter(f=>(!categoryFilter||f.categoryId===categoryFilter)&&(!kindFilter||f.type===kindFilter));}
  function renderList(){
    const box=$('#list'),scrollTop=box.scrollTop;box.replaceChildren();$('#count').textContent=`${p?.features.length||0} 个对象`;if(!p)return;
    if(!manager)return;
    const cats=$('#filter-category');if(categoryFilter&&!p.categories.some(c=>c.id===categoryFilter))categoryFilter='';cats.replaceChildren(el('option',{value:''},'全部分类'),...p.categories.map(c=>el('option',{value:c.id},c.name)));cats.value=categoryFilter;
    // Data table includes hidden layers; map visibility is an independent setting.
    const fs=tableFeatures();
    const category=f=>p.categories.find(c=>c.id===f.categoryId)?.name||'';
    fs.sort((a,b)=>sortBy==='name'?a.name.localeCompare(b.name,'zh-CN'):sortBy==='category'?category(a).localeCompare(category(b),'zh-CN'):String(b.updatedAt).localeCompare(String(a.updatedAt)));
    $('#result-count').textContent=`筛选结果 ${fs.length} / 共 ${p.features.length} 个 · 单击查看，双击定位地图`;
    if(!fs.length){box.append(el('p',{class:'empty'},'没有符合条件的标注'));return;}
    const table=el('table'),head=el('thead'),hr=el('tr');for(const text of ['名称','分类','类型','照片','标签','操作'])hr.append(el('th',{},text));head.append(hr);table.append(head);const body=el('tbody');
    for(const f of fs){const row=el('tr',{class:f.id===selected?'selected':'','data-id':f.id});const name=el('button',{'aria-label':`查看${f.name}`,class:'table-name'},f.name);name.onclick=()=>select(f.id);name.ondblclick=()=>locate(f.id);const cell=el('td');cell.append(name);row.append(cell,...[category(f),C.kinds[f.type],String(f.photos.length),f.tags.join('、')].map(t=>el('td',{},t)));const action=el('td'),loc=el('button',{'aria-label':`定位${f.name}`},'定位');loc.onclick=()=>locate(f.id);action.append(loc);row.append(action);body.append(row);}table.append(body);box.append(table);box.scrollTop=scrollTop;
  }
  function select(id,focus=false,remote=false){if(!p)return;selected=id;if(manager){if(remote&&!tableFeatures().some(f=>f.id===id)){query='';categoryFilter='';kindFilter='';$('#search').value='';$('#filter-kind').value='';renderList();toast('已清除筛选，以显示地图选中的标注。');}renderDetail();for(const row of $('#list').querySelectorAll('tr[data-id]'))row.classList.toggle('selected',row.dataset.id===id);if(remote)$('#list tr.selected')?.scrollIntoView({block:'nearest'});}else render();const f=p.features.find(f=>f.id===id);if(focus&&f)send('focus',{coordinate:f.coordinates[0]});if(!remote){bus.send({type:manager?'choose':'map-select',target:manager?mapPeer?.sender:null,projectId:p.id,id,focus:false});}if(!manager)window.scrollTo({top:$('#detail').offsetTop-12,behavior:'smooth'});}
  function locate(id){if(mapPeer?.busy){toast('地图正在绘制，请先完成或取消绘制再定位。');return;}if(!mapPeer||Date.now()-mapPeer.seen>6500||!mapPeer.ready){toast('地图未连接，请打开高德并等待连接后重试。');return;}bus.send({type:'choose',target:mapPeer.sender,projectId:p.id,id,focus:true});}
  function inputField(label,value,fn,type='text'){const wrap=el('label',{class:'field'},label),input=el(type==='textarea'?'textarea':'input',type==='textarea'?{}:{type});input.value=value;let last=String(value);const apply=()=>{if(input.value===last)return;const next=input.value;last=next;try{fn(next);}catch(e){toast(e.message);renderDetail();}};input.onchange=apply;input.onblur=apply;wrap.append(input);return wrap;}
  function renderDetail(){const f=p?.features.find(f=>f.id===selected),section=$('#detail'),box=$('#detail-form');section.hidden=!f;document.body.classList.toggle('has-detail',!!f);box.replaceChildren();if(!f)return;
    box.append(inputField('名称 / 显示文字',f.name,v=>commit(()=>f.name=v.trim())),el('p',{class:'hint'},`${C.kinds[f.type]} · GCJ-02 · ${f.id.slice(0,8)}`));
    const catWrap=el('label',{class:'field'},'分类'),sel=el('select',{'aria-label':'标注分类'});sel.append(...p.categories.map(c=>el('option',{value:c.id},c.name)));sel.value=f.categoryId;sel.onchange=()=>commit(()=>f.categoryId=sel.value);catWrap.append(sel);box.append(catWrap);
    if(['point','text','circle'].includes(f.type)){
      const coords=el('div',{class:'grid2'});['经度','纬度'].forEach((label,i)=>coords.append(inputField(label,f.coordinates[0][i].toFixed(6),v=>commit(()=>{if(!v.trim())throw Error('坐标不能为空');f.coordinates[0][i]=Number(v);}), 'number')));box.append(coords);
      if(f.type==='circle')box.append(inputField('半径（米，直线距离圈）',f.radius,v=>commit(()=>f.radius=Number(v)),'number'));
      const move=el('button',{class:'wide'},'⌖ 在地图上重新定位');move.disabled=!ready||manager;move.onclick=()=>setMode('edit',true);box.append(move);
    }else box.append(el('p',{class:'hint'},`${f.coordinates.length} 个地理顶点；编辑时拖动白色节点，点击金色中点添加节点。`));
    const shapeActions=el('div',{class:'grid2'}),editShape=el('button',{},'编辑形状'),moveShape=el('button',{},'整体移动');editShape.disabled=moveShape.disabled=!ready||manager;editShape.onclick=()=>setMode('edit');moveShape.onclick=()=>setMode('edit',true);shapeActions.append(editShape,moveShape);box.append(shapeActions);
    box.append(inputField('标签（逗号分隔）',f.tags.join('，'),v=>commit(()=>f.tags=v.split(/[,，]/).map(s=>s.trim()).filter(Boolean))),inputField('备注',f.notes,v=>commit(()=>f.notes=v),'textarea'));
    const fields=el('div');fields.append(el('div',{class:'section-head'},'自定义资料'));
    for(const [key,value]of Object.entries(f.fields)){const row=el('div',{class:'field-row'}),k=el('input',{'aria-label':'字段名称',value:key}),v=el('input',{'aria-label':key,value:String(value)}),del=el('button',{title:`删除字段${key}`},'×');k.onchange=()=>{try{commit(()=>{const next=k.value.trim();if(!next||['__proto__','constructor','prototype'].includes(next))throw Error('请使用其他字段名称');if(next!==key&&Object.hasOwn(f.fields,next))throw Error('字段名称重复');const val=f.fields[key];delete f.fields[key];f.fields[next]=val;});}catch(e){toast(e.message);renderDetail();}};v.onchange=v.onblur=()=>{if(String(f.fields[key])!==v.value)commit(()=>f.fields[key]=v.value);};del.onclick=()=>commit(()=>delete f.fields[key]);row.append(k,v,del);fields.append(row);}
    const add=el('button',{class:'link wide'},'＋ 添加字段');add.onclick=()=>commit(()=>{let n=1;while(Object.hasOwn(f.fields,`字段${n}`))n++;f.fields[`字段${n}`]='';});fields.append(add);box.append(fields);
    const photoTitle=el('div',{class:'section-head'},`照片 · ${f.photos.length}/20`);photoTitle.style.marginTop='17px';box.append(photoTitle);const photos=el('div',{class:'photos'});
    for(const a of f.photos){const tile=el('div',{class:'photo'}),img=el('img',{src:a.data,alt:a.name}),del=el('button',{title:`移除照片${a.name}`},'×');img.onclick=()=>{dialog(el('h3',{},a.name),el('img',{src:a.data,alt:a.name}));};del.onclick=()=>commit(()=>f.photos=f.photos.filter(v=>v.id!==a.id));tile.append(img,del,el('small',{},a.name));photos.append(tile);}box.append(photos);
    const upload=el('input',{type:'file',accept:'image/jpeg,image/png,image/webp',multiple:'',hidden:''}),addPhoto=el('button',{class:'wide'},photoBusy?'正在处理照片…':'＋ 添加本地照片');addPhoto.disabled=photoBusy;addPhoto.onclick=()=>upload.click();upload.onchange=async()=>{if(photoBusy)return;const targetId=f.id,projectId=p.id;photoBusy=true;renderDetail();try{const files=Array.from(upload.files);if(f.photos.length+files.length>20)throw Error('每个标注最多 20 张照片');const result=[];for(const file of files)result.push(await photo(file));if(p.id!==projectId)throw Error('项目已切换，请重新添加照片');const target=p.features.find(x=>x.id===targetId);if(!target)throw Error('标注已删除');commit(()=>target.photos.push(...result));}catch(e){toast(e.message);}finally{photoBusy=false;renderDetail();}};box.append(upload,addPhoto,el('p',{class:'hint'},'照片仅在本机处理，最长边压缩至 1600 像素；备份含压缩后的照片。'));
    const actions=el('div',{class:'grid2'});actions.style.marginTop='14px';const copy=el('button',{},'复制标注'),del=el('button',{class:'danger'},'删除标注');copy.onclick=()=>commit(()=>{const n=C.clone(f);n.id=C.uid();n.name+=' · 副本';n.createdAt=new Date().toISOString();p.features.push(n);selected=n.id;});del.onclick=()=>{commit(()=>{p.features=p.features.filter(x=>x.id!==f.id);selected='';});toast('已删除，可使用“撤销”恢复。');};actions.append(copy,del);box.append(actions);
  }
  async function photo(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>20*1024*1024)throw Error('照片需为 JPEG / PNG / WebP，单张不超过 20 MB。');const bmp=await createImageBitmap(file);try{const scale=Math.min(1,1600/Math.max(bmp.width,bmp.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bmp.width*scale);canvas.height=Math.round(bmp.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bmp,0,0,canvas.width,canvas.height);return{id:C.uid(),name:file.name.slice(0,200),data:canvas.toDataURL('image/jpeg',.82)};}finally{bmp.close();}}
  function render(){document.body.classList.toggle('no-project',!p);if(!p){renderProjects();renderTools();renderList();renderDetail();scene();return;}if(!p.categories.some(c=>c.id===activeCategory))activeCategory=p.categories[0].id;renderProjects();renderTools();renderCategories();renderList();renderDetail();scene();}
  function dialog(...nodes){$('#dialog-content').replaceChildren(...nodes);if(!$('#dialog').open)$('#dialog').showModal();}
  $('#dialog-close').onclick=()=>$('#dialog').close();
  function categoryMenu(c){const edit=el('button',{class:'wide'},'修改名称 / 颜色'),remove=el('button',{class:'wide danger'},'删除分类');edit.onclick=()=>categoryDialog(c);remove.onclick=()=>deleteCategoryDialog(c);remove.disabled=p.categories.length===1;dialog(el('h3',{},c.name),edit,remove,...(p.categories.length===1?[el('p',{},'最后一个分类需要保留，可以重命名。')]:[]));}
  function deleteCategoryDialog(c){
    const count=p.features.filter(f=>f.categoryId===c.id).length;
    const apply=(target,drop)=>{try{setMode('select');commit(()=>{p=C.removeCategory(p,c.id,target,drop);if(!p.features.some(f=>f.id===selected))selected='';});$('#dialog').close();toast(drop?'已删除分类及标注，可撤销恢复照片。':'分类已删除，标注已保留；可撤销。');}catch(e){toast(e.message);}};
    if(!count){apply(null,false);return;}
    const target=el('select',{'aria-label':'迁移到分类'});target.append(...p.categories.filter(v=>v.id!==c.id).map(v=>el('option',{value:v.id},v.name)));
    const migrate=el('button',{class:'wide primary'},`迁移 ${count} 个标注并删除分类`);migrate.onclick=()=>apply(target.value,false);
    const drop=el('button',{class:'wide danger'},`删除分类及 ${count} 个标注…`);drop.onclick=()=>{const confirm=el('button',{class:'wide danger'},`确认删除 ${count} 个标注及其照片`);confirm.onclick=()=>apply(null,true);dialog(el('h3',{},'确认删除分类及内容'),el('p',{},`将删除“${c.name}”中的全部 ${count} 个标注及关联照片，包括当前被筛选隐藏的内容。可在本次打开期间使用撤销恢复。`),confirm);};
    dialog(el('h3',{},`删除“${c.name}”`),el('p',{},`此分类共有 ${count} 个标注（包含搜索筛选隐藏的标注）。推荐先迁移，照片和资料会一起保留。`),target,migrate,drop);
  }
  function categoryDialog(c){const name=el('input',{'aria-label':'分类名称',value:c?.name||'',placeholder:'例如：文化景点'}),color=el('input',{type:'color',value:c?.color||'#147d6b','aria-label':'分类颜色'}),ok=el('button',{class:'primary wide'},'保存分类');ok.onclick=()=>{try{commit(()=>{if(c){c.name=name.value.trim();c.color=color.value;}else{const n={id:C.uid(),name:name.value.trim(),color:color.value,visible:true};p.categories.push(n);activeCategory=n.id;}});$('#dialog').close();}catch(e){toast(e.message);}};dialog(el('h3',{},c?'编辑分类':'新建分类'),name,el('p',{},'标注颜色'),color,ok);}
  function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=el('a',{href:url,download:name.replace(/[\\/:*?"<>|]/g,'_')});a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
  async function openProject(id){if(photoBusy||mode!=='select')throw Error('请先完成照片处理或地图绘制。');await saving;if(saveError||externalPending)throw Error('请先备份当前修改并载入最新数据，再切换项目。');projects=await S.list();const found=projects.find(v=>v.id===id);if(!found){p=null;render();return;}p=C.validate(found);revisions.set(p.id,p.revision||0);activeCategory=p.categories[0].id;selected='';undo=[];redo=[];query='';categoryFilter='';$('#search').value='';setMode('select');render();presence();}
  function projectDialog(rename=false){const name=el('input',{'aria-label':'项目名称',value:rename?p.name:'',placeholder:'例如：杭州西湖旅游区位图'}),template=el('select',{'aria-label':'项目模板'});template.append(...['综合','地产','旅游','城市规划'].map(v=>el('option',{value:v},v)));const ok=el('button',{class:'primary wide'},rename?'保存名称':'创建项目');ok.onclick=async()=>{try{if(!name.value.trim())throw Error('请填写项目名称');if(rename)commit(()=>p.name=name.value.trim());else{await saving;if(saveError)throw saveError;const next=C.project(name.value.trim(),template.value);C.validate(next);const out=await S.save(next,0);projects.push(out);await openProject(out.id);}$('#dialog').close();}catch(e){toast(e.message);}};dialog(el('h3',{},rename?'重命名项目':'新的区位观察'),name,...(rename?[]:[el('p',{},'选择一套初始分类，之后可以自行修改。'),template]),ok);}
  let labelChoiceDirty=false;
  on('#hide-full','change',()=>{labelChoiceDirty=true;});
  on('#hide-poi','change',e=>send('poi-labels',{hidden:e.target.checked}));
  on('#apply-labels','click',async()=>{if(mode!=='select')throw Error('请先完成或取消正在绘制 / 编辑的图形。');if(photoBusy)throw Error('照片正在处理，请稍后再应用。');await persist();await saving;if(saveError)throw Error('保存失败，请先备份项目，暂不刷新。');send('full-labels',{hidden:$('#hide-full').checked});});
  on('#new-project','click',()=>projectDialog());on('#rename-project','click',()=>projectDialog(true));on('#projects','change',e=>openProject(e.target.value));
  on('#add-category','click',()=>categoryDialog());on('#close-detail','click',()=>{selected='';render();});
  on('#search','input',e=>{query=e.target.value;renderList();});
  on('#filter-category','change',e=>{categoryFilter=e.target.value;renderList();});on('#filter-kind','change',e=>{kindFilter=e.target.value;renderList();});on('#sort-list','change',e=>{sortBy=e.target.value;renderList();});
  for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>setMode(b.dataset.mode);
  on('#cancel','click',()=>setMode('select'));on('#back-vertex','click',()=>{draft.pop();renderTools();scene();});
  on('#finish','click',()=>{const type=mode,coords=C.clone(draft);if(coords.length<(type==='line'?2:3))return;commit(()=>{const f=C.feature(type,coords,activeCategory);p.features.push(f);selected=f.id;});setMode('select');render();});
  on('#undo','click',()=>{if(!undo.length)return;redo.push(C.clone(p));p=undo.pop();selected='';setMode('select');persist();render();});
  on('#redo','click',()=>{if(!redo.length)return;undo.push(C.clone(p));p=redo.pop();selected='';setMode('select');persist();render();});
  on('#export-project','click',()=>download(`${p.name}.amapnotes`,C.backup(p)));
  on('#export-csv','click',()=>download(`${p.name}-点位.csv`,C.toCSV(p,manager?tableFeatures():C.visible(p,query)),'text/csv;charset=utf-8'));
  $('#import-project').onclick=()=>$('#file-project').click();$('#import-csv').onclick=()=>$('#file-csv').click();
  on('#file-project','change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>100*1024*1024)throw Error('备份文件不能超过 100 MB');const next=C.restore(await file.text());const confirm=el('button',{class:'primary wide'},'恢复为新项目');confirm.onclick=async()=>{try{await saving;if(saveError)throw saveError;const out=await S.save(next,0);projects.push(out);await openProject(out.id);$('#dialog').close();toast('已恢复为新项目，原项目保留。');}catch(e){toast(e.message);}};dialog(el('h3',{},'恢复项目'),el('p',{},`${next.name}：${next.features.length} 个标注，${next.features.reduce((n,f)=>n+f.photos.length,0)} 张照片。`),confirm);});
  on('#file-csv','change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>10*1024*1024)throw Error('CSV 不可超过 10 MB');const input=await file.text(),rows=C.parseCSV(input),head=rows[0],mapping={};const box=el('div');box.append(el('h3',{},'导入点位'),el('p',{},'选择对应的表格列。仅接受 GCJ-02；按编号更新，空白可选字段保留原值。照片不受影响。'));const labels={id:'编号',name:'名称 *',longitude:'经度 *',latitude:'纬度 *',crs:'坐标系 *',category:'分类',tags:'标签 JSON',notes:'备注',fields:'字段 JSON'};for(const k of C.headers){const row=el('label',{class:'mapping'},labels[k]),sel=el('select',{'aria-label':`映射${labels[k]}`});sel.append(el('option',{value:'-1'},'不导入'),...head.map((h,i)=>el('option',{value:i},h)));sel.value=String(head.indexOf(k));mapping[k]=head.indexOf(k);sel.onchange=()=>mapping[k]=Number(sel.value);row.append(sel);box.append(row);}const preview=el('button',{class:'primary wide'},'检查导入内容');preview.onclick=()=>{try{const plan=C.planCSV(p,input,mapping),nodes=[el('h3',{},'导入预览'),el('p',{},`新增 ${plan.added} 个，更新 ${plan.updated} 个。`)];if(plan.errors.length)nodes.push(el('p',{class:'error-text'},'发现错误，未写入任何数据。请修正 CSV 后重试。'),el('pre',{},plan.errors.slice(0,20).join('\n')));else{const apply=el('button',{class:'primary wide'},'确认导入');apply.onclick=()=>{try{commit(()=>p=plan.project);setMode('select');$('#dialog').close();toast('导入完成，可撤销。');}catch(e){toast(e.message);}};nodes.push(apply);}dialog(...nodes);}catch(e){toast(e.message);}};box.append(preview);dialog(box);});
  window.addEventListener('message',e=>{if(e.source!==parent||e.origin!==parentOrigin||e.data?.channel!=='region-notes-panel')return;const q=e.data;if(!p)return;try{
    if(q.type==='label-status'){$('#hide-poi').disabled=!q.supported;$('#hide-poi').checked=q.poiHidden;if(!labelChoiceDirty)$('#hide-full').checked=q.fullHidden;}
    if(q.type==='status'){ready=!!q.ready;$('#map-status').textContent=ready?'● 高德已连接':'○ 等待地图连接';$('#map-status').className=ready?'ready':'';renderTools();}
    if(q.type==='error')toast(q.message);
    if(q.type==='cancel')setMode('select');
    if(q.type==='select')select(q.id);
    if(q.type==='status')presence();
    if(q.type==='editor-commit'&&ready&&mode!=='select'&&!$('#dialog').open){
      const shape=q.geometryType;C.shapeOK(shape,q.coordinates,q.radius);
      if(mode==='edit'){const f=p.features.find(f=>f.id===selected);if(!f||q.id!==f.id||f.type!==shape)throw Error('编辑对象已变化，请重新选择。');commit(()=>{f.coordinates=C.clone(q.coordinates);if(shape==='circle')f.radius=q.radius;f.updatedAt=new Date().toISOString();});}
      else{if(shape!==mode)throw Error('绘制工具已变化，请重试。');commit(()=>{const f=C.feature(shape,C.clone(q.coordinates),activeCategory);if(shape==='circle')f.radius=q.radius;p.features.push(f);selected=f.id;});}
      setMode('select');render();bus.send({type:'map-select',projectId:p.id,id:selected});window.scrollTo({top:$('#detail').offsetTop-12,behavior:'smooth'});
    }

  }catch(err){toast(err.message);if(q.type==='editor-commit')send('editor-reject',{message:err.message});}});
  document.addEventListener('keydown',e=>{if(mode==='select'||$('#dialog').open||e.target.closest('input,textarea,select,[contenteditable]'))return;if(['Enter','Escape','Backspace','Delete'].includes(e.key)){e.preventDefault();send('editor-key',{key:e.key});}});
  function presence(){if(!manager)bus.send({type:'presence',projectId:p?.id,ready,busy:mode!=='select'});}
  function editing(){return photoBusy||mode!=='select'||$('#dialog').open||document.activeElement?.matches('input,textarea,select');}
  async function refresh(force=false){const previous=p;await saving;const fresh=await S.list();if(p!==previous||(!force&&(editing()||saveError))){externalPending=true;$('#sync-notice').hidden=false;return;}projects=fresh;if(p&&projects.some(v=>v.id===p.id)){p=C.validate(projects.find(v=>v.id===p.id));revisions.set(p.id,p.revision||0);}else{p=projects[0]?C.validate(projects[0]):null;selected='';if(p)revisions.set(p.id,p.revision||0);}undo=[];redo=[];externalPending=false;$('#sync-notice').hidden=true;render();presence();}
  bus.on(q=>{if(!q)return;
    if(q.type==='presence'&&manager){if(mapPeer&&mapPeer.sender!==q.sender&&Date.now()-mapPeer.seen<6500)return;mapPeer={...q,seen:Date.now()};$('#map-status').textContent=q.ready?'● 地图已连接':'○ 地图尚未连接';return;}
    if(q.type==='changed'){refreshTask=refreshTask.then(async()=>{await saving;if(p&&q.projectId!==p.id){projects=await S.list();renderProjects();return;}if(editing()||saveError){externalPending=true;$('#sync-notice').hidden=false;return;}await refresh();}).catch(e=>toast(e.message));}
    if(q.type==='map-select'&&manager){refreshTask=refreshTask.then(async()=>{if(editing()||saveError||externalPending){toast('地图选择已变化；请先完成当前编辑。');return;}if(p?.id!==q.projectId)await openProject(q.projectId);select(q.id,false,true);}).catch(e=>toast(e.message));}
    if(q.type==='choose'&&!manager&&q.target===bus.id){refreshTask=refreshTask.then(async()=>{if(editing()||saveError||externalPending){bus.send({type:'presence',ready:false,projectId:p?.id});toast('管理窗口请求定位，请先完成当前编辑。');return;}if(p?.id!==q.projectId)await openProject(q.projectId);select(q.id,!!q.focus,true);}).catch(e=>toast(e.message));}
  });
  on('#reload-data','click',async()=>{if(photoBusy||mode!=='select')throw Error('请先完成或取消当前操作。');const apply=el('button',{class:'primary wide'},'放弃本窗口未保存内容并载入');apply.onclick=async()=>{saveError=null;await refresh(true);$('#dialog').close();};dialog(el('h3',{},'载入最新数据'),el('p',{},'如果本窗口有保存失败的修改，请先关闭此提示并导出完整备份。载入后将清空本窗口撤销记录。'),apply);});
  on('#open-manager','click',async()=>{if(globalThis.chrome?.runtime?.id){const result=await chrome.runtime.sendMessage({type:'open-manager',projectId:p?.id});if(result?.error)throw Error(result.error);if(p)bus.send({type:'map-select',projectId:p.id,id:selected});}else{const win=window.open('panel.html?manager=1&project='+encodeURIComponent(p?.id||''),'amap-notes-manager','width=1280,height=820');if(!win)throw Error('请允许弹出数据管理窗口。');win.focus();}});
  on('#delete-project','click',()=>{if(!p)return;const target=p;const remove=el('button',{class:'danger wide'},'移入回收站'),backup=el('button',{class:'wide'},'先导出完整备份');backup.onclick=()=>download(`${target.name}.amapnotes`,C.backup(target));remove.onclick=async()=>{try{await saving;if(saveError)throw saveError;if(externalPending)throw Error('请先载入最新数据，再删除项目。');if(photoBusy||mode!=='select')throw Error('请先完成当前操作。');await S.trash(target.id,revisions.get(target.id)||0);$('#dialog').close();await refresh();toast('项目已移入回收站，可随时恢复。');}catch(e){toast(e.message);}};dialog(el('h3',{},`删除项目：${target.name}`),el('p',{},`包含 ${target.features.length} 个标注、${target.features.reduce((n,f)=>n+f.photos.length,0)} 张照片。项目会保存在本地回收站，直到你永久删除。`),backup,remove);});
  async function showTrash(){const items=await S.list(true),box=el('div');box.append(el('h3',{},'项目回收站'));if(!items.length)box.append(el('p',{},'回收站为空'));for(const v of items){const row=el('div',{class:'trash-item'}),restore=el('button',{},'恢复项目'),purge=el('button',{class:'danger'},'永久删除');restore.onclick=async()=>{try{await S.restore(v.id,v.revision);await refresh(true);await showTrash();}catch(e){toast(e.message);}};purge.onclick=()=>{const confirm=el('button',{class:'danger wide'},'确认永久删除');confirm.onclick=async()=>{try{await S.purge(v.id,v.revision);await showTrash();}catch(e){toast(e.message);}};dialog(el('h3',{},`永久删除“${v.name}”？`),el('p',{},'将移除全部标注和照片，无法通过回收站恢复。'),confirm);};row.append(el('strong',{},v.name),el('p',{},`${v.features.length} 个标注 · 删除于 ${new Date(v.deletedAt).toLocaleString()}`),restore,purge);box.append(row);}dialog(box);}
  on('#trash-projects','click',showTrash);
  // Reuse the same forms, photos and import/export flows in both surfaces.
  if(manager){$('#toggle-projects').hidden=false;$('#toggle-projects').onclick=()=>{const collapsed=document.body.classList.toggle('projects-collapsed');$('#toggle-projects').textContent=collapsed?'展开项目栏':'收起项目栏';$('#toggle-projects').setAttribute('aria-expanded',String(!collapsed));};$('#open-manager').hidden=true;$('#drawing-section').hidden=true;$('#map-labels').hidden=true;const project=$('.project');project.append($('#layers-section'),$('.files'));for(const node of [$('#layers-section'),$('.files')]){const wrap=el('details'),summary=el('summary',{},node.querySelector('h2').textContent);node.before(wrap);wrap.append(summary,node);}const undoBar=$('#undo').parentElement;$('#list-section').prepend(undoBar);$('#map-status').textContent='○ 未连接地图 · 可管理本地资料';$('.brand strong').textContent='区位笔记 · 数据管理';$('.files .hint').textContent='CSV 导出表格筛选后的点位；完整备份包含全部图形与照片。';}
  else{const main=$('main');main.prepend($('.project'));$('#list-section').hidden=true;for(const node of [$('#layers-section'),$('#map-labels'),$('.files')]){const wrap=el('details'),summary=el('summary',{},node.querySelector('h2').textContent);if(node.id==='layers-section')wrap.open=true;node.before(wrap);wrap.append(summary,node);}}
  try{projects=await S.list();if(!projects.length&&!(await S.hasAny())){const out=await S.save(C.project(),0);projects=[out];}const requested=new URLSearchParams(location.search).get('project');p=projects.length?C.validate(projects.find(v=>v.id===requested)||projects.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0]):null;if(p){revisions.set(p.id,p.revision||0);activeCategory=p.categories[0].id;}render();$('#save-status').textContent='已保存在本机';send('hello');presence();setInterval(()=>{presence();if(manager&&mapPeer&&Date.now()-mapPeer.seen>6500){mapPeer=null;$('#map-status').textContent='○ 地图已断开 · 可管理本地资料';}},2000);}catch(e){$('#save-status').textContent='无法读取本地数据';$('#save-status').className='error';toast(e.message);}
})();
